spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/movies
    username: root
    password: Ilove98u

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


project:
  poster: posters/